##### Installing Tensorflow
- pip install tensorflow

tensorflow is a powerful open-source library for machine learning and deep learning. It provides a flexible ecosystem of tools, libraries, and community resources that lets researchers and developers build and deploy machine learning models easily. With TensorFlow, you can create complex neural networks, perform data manipulation, and run computations efficiently on various hardware platforms, including CPUs, GPUs, and TPUs. Whether you're working on image recognition, natural language processing, or any other machine learning task, TensorFlow offers the capabilities to help you achieve your goals.

##### Installing Keras
- pip install keras

keras is a high-level neural networks API, written in Python and capable of running on top of TensorFlow.

##### Step-1 Business Problem Understanding
Predict/estimate the wind energy based on atmospheric conditions

##### Step-2 
- Load the data 
- data understanding
- data exploration

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('energy.xlsx')
df

         AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [3]:
df.shape

(9568, 5)

**Data Understanding**

In [4]:
df.columns.tolist()

['AT', 'V', 'AP', 'RH', 'PE']

**Data Exploration**

In [5]:
df["AT"].unique()

array([14.96, 25.18,  5.11, ..., 30.  ,  5.01,  9.71], shape=(2773,))

In [6]:
df["AP"].unique()

array([1024.07, 1020.04, 1012.16, ..., 1027.12, 1024.16, 1023.67],
      shape=(2517,))

**Data Cleaning**

In [7]:
l = []
for i in df["AP"] : 
    if type(i) not in [int, float] : 
        l.append(i)
print(l)

[]

In [8]:
## if wrong data is there then we can drop that row or we can fill that row with mean or median value of that column.
df[df["AP"] == "no data"].index.tolist()
df.loc[258, "AP"] = df["AP"].mean() # or replace with orginal data if you have that data

**Input and Ouput Variables**

In [9]:
x = df.drop("PE", axis=1)
y = df["PE"]

**Splitting the data into training and testing data**

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
# above code will split the data into 80% training data and 20% testing data. random_state is used to get the same split every time we run the code.
# random_state is used to get the same split every time we run the code. if we do not set random_state then we will get different split every time we run the code.
# we can set any number for random_state.

In [11]:
x_train

         AT      V       AP     RH
5487  21.92  49.02  1009.29  88.56
3522  11.09  40.43  1025.47  74.97
6916   8.49  39.61  1021.05  87.74
7544  11.43  44.78  1013.43  82.45
7600  17.28  39.99  1007.09  74.25
...     ...    ...      ...    ...
5734  23.39  61.87  1010.35  48.91
5191  11.63  40.55  1022.89  87.12
5390  27.79  69.23  1012.86  45.71
860   12.26  41.50  1014.87  89.41
7270  11.75  40.55  1018.09  97.70

[7654 rows x 4 columns]

In [12]:
y_train

5487    443.31
3522    490.96
6916    483.94
7544    471.09
7600    463.28
         ...
5734    444.03
5191    474.67
5390    435.06
860     471.13
7270    472.43
Name: PE, Length: 7654, dtype: float64

##### Perceptron

In [13]:
import tensorflow as tf
import keras

In [14]:
from keras.models import Sequential
from keras.layers import Dense

**Design the perceptron model**

In [15]:
## initialize of neural network
model = Sequential()

## add input layer and first hidden layer
model.add(Dense(input_dim=4, units=1, activation="relu", kernel_initializer="uniform")) 
# input_dim is number of features in the data. units is number of neurons in the hidden layer. activation is activation function used in the hidden layer.
# kernel_initializer is used to initialize the weights of the neurons. we can use uniform or normal distribution to initialize the weights.
# dense connects all the neurons in the previous layer to all the neurons in the next layer.

# compile - calculate the loss and optimizer
model.compile(loss="mean_squared_error", optimizer="adam")

c:\Users\nirmi\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [ ]:
# fit the train data to the model for calculating the weights and bias of the neurons.
model.fit(x_train, y_train, epochs=100, batch_size=32)

In [ ]:
### Prediction on train data
y_train_pred = model.predict(x_train)
y_train_pred

## evaulate the