### 6. Text Clustering Projects

**Non-Sequential Data**
- if o/p is available : labelled Data --> supervised ML (regression or classification)
- if o/p is not available : unlabelled Data --> unsupervised ML (clustering)

In [2]:
import pandas as pd

In [3]:
npr = pd.read_csv('npr.csv')
npr.head()

                                             Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
npr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Article  200 non-null    object
dtypes: object(1)
memory usage: 1.7+ KB

#### Text Preprocessing
##### Text Cleaning
One of the main reason is to reduce the input columns
- Remove Punctuation
- Remove Stopwords
- Stemming

In [16]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()

corpus = []
for i in range(0, len(npr)):
    rp = re.sub('[^a-zA-Z]', ' ', npr['Article'][i])
    rp = rp.lower()
    rp = rp.split()
    rp = [wnl.lemmatize(word) for word in rp if not word in set(stopwords.words('english'))]
    rp = ' '.join(rp)
    corpus.append(rp)

print(corpus[0])

washington even policy bipartisan politics cannot sense year show little sign ending dec president obama moved sanction russia alleged interference u election concluded republican long called similar severe measure could scarcely bring approve house speaker paul ryan called obama measure appropriate also overdue prime example administration ineffective foreign policy left america weaker eye world gop leader sounded much theme urging president obama year take strong action deter russia worldwide aggression including operation wrote rep devin nunes chairman house intelligence committee week left office president suddenly decided stronger measure indeed warranted appearing cnn frequent obama critic trent frank called much tougher action said three time obama finally found tongue meanwhile fox news various spokesman trump said obama real target russian man poised take white house less three week spoke obama trying tie trump hand box meaning would forced either keep sanction odds republican want tougher still moscow throughout trump repeatedly called sanction closer tie russia including cooperation fight isi russia battled isi syria behalf country embattled dictator bashar assad bombing besieged city aleppo fell assad force week campaign trump even urged russia find missing email private server opponent hillary clinton exchanged public encomium russian president vladimir putin several occasion added doubt current u level support nato putin longtime nemesis also suggestion trump extensive business dealing various russian reason refuse release tax return issue disquieting republican many month sen john mccain lindsay graham c prominent senior member armed service committee accepted assessment u intelligence agency regarding role russia hacking various democratic committee last year includes fbi cia consensus russian goal discredit american democracy defeat clinton elect trump say great majority senate colleague agree mccain slated armed service hearing cyberthreats jan politicizing russian action idea helped trump win also made issue difficult republican leader allowed trump supporter push back intelligence agency say entire issue designed undermine trump legitimacy senate majority leader mitch mcconnell far resisted call select committee look russian interference campaign said enough sen richard burr c look chairman senate intelligence committee typically republican leader spokesman say evidence actual voting tallying nov compromised true also red herring interference function alleged focus u intelligence agency concern part trump shown little interest delving happened cast doubt u intelligence report date suggested one really know happened also suggested computer make difficult know using week trump said time get life important thing however week end agree intelligence briefing subject next week wanted daily intelligence briefing available recent week preferring given men chosen vice president mike penny national security adviser mike flynn trump taking occasionally irony controversy arising eleventh hour obama presidency scarcely overstated defines dilemma facing outgoing president incoming party control obama appears reluctant retaliate russian hacking election fear seeming interfere election republican meanwhile year called greater confrontation russian obama usually resisting obama join nato punishing russian economic sanction annexation crimea sanction may painful coming alongside falling price oil commodity keep russian economy afloat occasion despite russian provocation surrogate syria elsewhere obama make overt move force russia hand includes occasion russia believed hacking critical computer system neighboring ukraine estonia poland week following chorus confirmation u intelligence community regarding russian role computer hacking political campaign obama acted imposed set mostly diplomatic action sanctioning russian official closing two diplomatic compound expelling russian diplomat may damaging measure taken covertly russophobes washington held hope visible portion program scarcely amounted major retribution putin saw fit diminish obama sanction declining respond although government steadfastly denied interference u election putin rejected foreign minister recommended package response even sent invitation u diplomat send child holiday party moscow allowed putin appear moment bigger man even spurned obama kept looked like public bromance trump tweeted great move delay v putin always knew smart moment may seem overall russia question amount first crisis facing trump presidency whether forced campaign interference issue trump must grasp nettle relationship mitt romney called greatest threat u security world sure trump need dispel doubt ability stand putin bullied cajoled way center stage recent world affair trump also seems determined turn page past u commitment free trade philosophy funding nato united nation twitter account guide trump show little concern conundrum others perceive facing trump shown determined play rule year ago many confident would work world presidential politics find whether work oval office

##### Vectorization

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(200, 12008))

In [7]:
X.shape

(200, 12008)

#### Modelling using LDA

In [8]:
from sklearn.decomposition import LatentDirichletAllocation

model = LatentDirichletAllocation(n_components=3)
model.fit(X)

# In this algorithm we have to specify the number of topics we want to find. 
# Here we are looking for 3 topics. This works by finding the most common word in 
# each topic and then grouping the articles based on those words.
# Euclidean Distance is used to find the distance between the articles and the topics.
# The closer the article is to the topic, the more likely it is to belong to that topic.

LatentDirichletAllocation(n_components=3)

In [9]:
topic_results = model.transform(X)
# Here we have 3 topics and the values represent the 
# probability of each article belonging to each topic

In [10]:
topic_results[0]

array([9.98839235e-01, 5.50194547e-04, 6.10570444e-04])

In [11]:
topic_results[0].argmax()
# This means that the first article belongs to the second topic (index 1) 
# because it has the highest probability.

np.int64(0)

##### Combinining with Original Data

In [12]:
npr['group'] = topic_results.argmax(axis=1)
npr.head()
# Here we are adding a new column to the original dataframe 
# that contains the topic group for each article.

                                             Article  group
0  In the Washington of 2016, even when the polic...      0
1    Donald Trump has used Twitter  —   his prefe...      0
2    Donald Trump is unabashedly praising Russian...      0
3  Updated at 2:50 p. m. ET, Russian President Vl...      0
4  From photography, illustration and video, to d...      0

Showing top words per topic

In [13]:
for index, topic in enumerate(model.components_):
    print(f'The top 10 words for topic {index} are:')
    print([cv.get_feature_names_out()[i] for i in topic.argsort()[-10:]])
    print('\n')

The top 10 words for topic 0 are:
['would', 'time', 'new', 'said', 'people', 'like', 'one', 'year', 'trump', 'say']


The top 10 words for topic 1 are:
['would', 'way', 'new', 'time', 'like', 'said', 'year', 'one', 'people', 'say']


The top 10 words for topic 2 are:
['trump', 'new', 'one', 'people', 'republican', 'like', 'time', 'year', 'said', 'say']

In [15]:
npr[npr['group'] == 0]

                                               Article  group
0    In the Washington of 2016, even when the polic...      0
1      Donald Trump has used Twitter  —   his prefe...      0
2      Donald Trump is unabashedly praising Russian...      0
3    Updated at 2:50 p. m. ET, Russian President Vl...      0
4    From photography, illustration and video, to d...      0
..                                                 ...    ...
195  Mothers should feel comfortable   infants in p...      0
196  In South Korea, preparing for the worst has be...      0
197  David Bowie had long wanted to make a record w...      0
198  Chances are your doctor has stopped taking not...      0
199  French police have reportedly arrested more th...      0

[89 rows x 2 columns]